import { Header } from './components/header/Header';
import './globals.scss';

export const metadata = {
   title: 'LLV',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body>
            <Header />
            {children}
         </body>
      </html>
   );
}
